// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzDGkrVo4ZtLMUy66K_PhehACjhQe0_zY',
    appId: '1:619293720965:web:93b6f923e0101d9acc04ec',
    messagingSenderId: '619293720965',
    projectId: 'blood-d-27832',
    authDomain: 'blood-d-27832.firebaseapp.com',
    storageBucket: 'blood-d-27832.appspot.com',
    measurementId: 'G-Z7X04NXJ7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkTOHuhI354sVnDHHfj22oYB0T4bJ_mvM',
    appId: '1:619293720965:android:d0a64a61b56f5d0fcc04ec',
    messagingSenderId: '619293720965',
    projectId: 'blood-d-27832',
    storageBucket: 'blood-d-27832.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVJHke9OdsA4BMRWTfrLgJ93ZPU2Y9Sxw',
    appId: '1:619293720965:ios:eeef1bd88117c0b4cc04ec',
    messagingSenderId: '619293720965',
    projectId: 'blood-d-27832',
    storageBucket: 'blood-d-27832.appspot.com',
    iosBundleId: 'com.example.b',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVJHke9OdsA4BMRWTfrLgJ93ZPU2Y9Sxw',
    appId: '1:619293720965:ios:3de39aaf8950b47acc04ec',
    messagingSenderId: '619293720965',
    projectId: 'blood-d-27832',
    storageBucket: 'blood-d-27832.appspot.com',
    iosBundleId: 'com.example.b.RunnerTests',
  );
}
